backend:
backend:
  name: github
  repo: rodrig0miranda/site-ianas
  branch: main
  base_url: https://sveltia-cms-auth.pages.dev

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "src/pages/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data da Publicação", name: "date", widget: "datetime"}
      - {label: "Imagem de Capa", name: "thumbnail", widget: "image", required: false}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}